### ISSUE TITLE
all-day flag is not set

### ISSUE THREAD

**Issue by andylytical** [ncsa/vacation_calendar_sync#11]
On the Mac Outlook client, results in the start & end times being displayed, which then blocks the event Title.
![Screenshot 2023-08-23 at 12 25 31 PM](https://github.com/ncsa/vacation_calendar_sync/assets/7127884/125d20f0-3cf3-4097-b5ed-52c1f57b80de)

**Comment by billglick** [comment]
It is even uglier on the iOS Calendar app. I'd guess other apps may look similar.
![image](https://github.com/ncsa/vacation_calendar_sync/assets/910479/639f467c-eb75-4c3f-8bac-dfb99e735b05)

**Comment by PhongT16** [comment]
The problem should be fixed now!

**Comment by billglick** [comment]
I confirm that it resolves the issues I was seeing with Mac Outlook and iOS Calendar. Thanks!
